version: '3.8'

volumes:
  db-config:
  db-data:
    name: db-data

services:
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html

  server:
    build:
      context: ./backend/
    container_name: server
    restart: "on-failure"
    expose:
      - 8080
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3308:3306"
    expose:
      - 3306
    restart: always
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zoLZak@!1321
      - MYSQL_USER: root
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    networks:
      - default
